spec:
  template:
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: openshift
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 80
            scheme: HTTP
          initialDelaySeconds: 20